 
CREATE TABLE viewer 
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) DEFAULT NULL,
  birth date DEFAULT NULL,
  e_mail varchar(255) UNIQUE,
  city varchar(255) DEFAULT NULL
);

/*



CREATE TABLE viewer 
(
  ID bigint NOT NULL,
  BIRTH date DEFAULT NULL,
  CITY varchar(255) DEFAULT NULL,
  E_MAIL varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID), 
  UNIQUE KEY UK5awx5dcb9xdv5m1bl38bmoke0 (E_MAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci 

CREATE TABLE registry 
(
  `id` bigint NOT NULL,
  `author` varchar(255) DEFAULT NULL,
  `media` varchar(255) DEFAULT NULL,
  `production_date` date DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |

 
CREATE TABLE assessment (
  `id` bigint NOT NULL,
  `favorite` int NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `recommend` int NOT NULL,
  `registered_at` datetime(6) DEFAULT NULL,
  `registry_id` bigint DEFAULT NULL,
  `viewer_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKdbowthpvnkq7v1h0p9805m2ia` (`viewer_id`,`registry_id`),
  KEY `FKlwbgrgs2luy9tm0dh08e6d8u2` (`registry_id`),
  CONSTRAINT `FKi3gskegxme91qm3uf5l2kuyd7` FOREIGN KEY (`viewer_id`) REFERENCES `viewer` (`id`),
  CONSTRAINT `FKlwbgrgs2luy9tm0dh08e6d8u2` FOREIGN KEY (`registry_id`) REFERENCES `registry` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |

 */


/* spring academy example
CREATE TABLE cash_card
(
    ID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AMOUNT NUMBER NOT NULL DEFAULT 0
); 
*/  
